<<<<<<< HEAD
CRITICAL - 2021-09-02 17:26:19 --> Undefined offset: 0
#0 D:\xampp7.0\htdocs\iot\api\app\Controllers\Login.php(27): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', 'D:\\xampp7.0\\htd...', 27, Array)
#1 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Login->ValidarSesion()
#2 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-02 17:26:27 --> Undefined index: clave
#0 D:\xampp7.0\htdocs\iot\api\app\Controllers\Login.php(27): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'D:\\xampp7.0\\htd...', 27, Array)
#1 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Login->ValidarSesion()
#2 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-02 17:26:33 --> Undefined index: clave
#0 D:\xampp7.0\htdocs\iot\api\app\Controllers\Login.php(27): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'D:\\xampp7.0\\htd...', 27, Array)
#1 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Login->ValidarSesion()
#2 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-02 17:26:48 --> Undefined offset: 4
#0 D:\xampp7.0\htdocs\iot\api\app\Controllers\Login.php(27): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', 'D:\\xampp7.0\\htd...', 27, Array)
#1 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Login->ValidarSesion()
#2 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-02 17:26:54 --> Undefined index: clave
#0 D:\xampp7.0\htdocs\iot\api\app\Controllers\Login.php(27): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'D:\\xampp7.0\\htd...', 27, Array)
#1 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Login->ValidarSesion()
#2 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-02 17:27:01 --> Undefined index: clave
#0 D:\xampp7.0\htdocs\iot\api\app\Controllers\Login.php(27): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'D:\\xampp7.0\\htd...', 27, Array)
#1 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Login->ValidarSesion()
#2 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-02 17:52:36 --> Undefined property: App\Controllers\Login::$load
#0 D:\xampp7.0\htdocs\iot\api\app\Controllers\Login.php(54): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xampp7.0\\htd...', 54, Array)
#1 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Login->RestablecerPassword()
#2 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-02 17:55:00 --> Undefined property: App\Controllers\Login::$email
#0 D:\xampp7.0\htdocs\iot\api\app\Controllers\Login.php(15): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xampp7.0\\htd...', 15, Array)
#1 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(900): App\Controllers\Login->__construct()
#2 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(426): CodeIgniter\CodeIgniter->createController()
#3 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-02 17:55:55 --> Call to a member function initialize() on null
#0 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(900): App\Controllers\Login->__construct()
#1 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(426): CodeIgniter\CodeIgniter->createController()
#2 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-09-02 17:56:21 --> Undefined property: App\Controllers\Login::$load
#0 D:\xampp7.0\htdocs\iot\api\app\Controllers\Login.php(56): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xampp7.0\\htd...', 56, Array)
#1 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Login->RestablecerPassword()
#2 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-02 17:59:54 --> Undefined property: App\Controllers\Login::$load
#0 D:\xampp7.0\htdocs\iot\api\app\Controllers\Login.php(56): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xampp7.0\\htd...', 56, Array)
#1 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Login->RestablecerPassword()
#2 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-02 18:00:07 --> Call to a member function from() on null
#0 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Login->RestablecerPassword()
#1 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-09-02 18:00:23 --> Call to a member function initialize() on null
#0 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(900): App\Controllers\Login->__construct()
#1 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(426): CodeIgniter\CodeIgniter->createController()
#2 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-09-02 18:01:31 --> Call to a member function initialize() on null
#0 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Login->RestablecerPassword()
#1 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-09-02 18:03:47 --> Call to a member function initialize() on null
#0 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(900): App\Controllers\Login->__construct()
#1 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(426): CodeIgniter\CodeIgniter->createController()
#2 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2021-09-02 18:03:56 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 18:08:34 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 18:08:48 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 18:11:11 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 18:12:43 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 18:14:02 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 18:15:07 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 18:16:53 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 18:17:21 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 18:18:14 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 18:20:16 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 18:21:41 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 18:23:11 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 18:27:41 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 18:28:50 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 18:29:18 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 18:35:12 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 18:43:39 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
CRITICAL - 2021-09-02 18:44:21 --> Undefined property: App\Controllers\Login::$load
#0 D:\xampp7.0\htdocs\iot\api\app\Controllers\Login.php(58): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xampp7.0\\htd...', 58, Array)
#1 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Login->RestablecerPassword()
#2 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2021-09-02 18:54:54 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 18:55:38 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
CRITICAL - 2021-09-02 19:17:26 --> Undefined property: App\Controllers\Login::$load
#0 D:\xampp7.0\htdocs\iot\api\app\Controllers\Login.php(18): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xampp7.0\\htd...', 18, Array)
#1 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(900): App\Controllers\Login->__construct()
#2 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(426): CodeIgniter\CodeIgniter->createController()
#3 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2021-09-02 19:17:40 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 19:19:42 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;smtp.gmail.com&quot; port 465, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 19:20:03 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;smtp.gmail.com&quot; port 465, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-09-02 19:20:17 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;smtp.gmail.com&quot; port 465, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
CRITICAL - 2021-09-02 19:34:42 --> require(./PHPMailer/PHPMailer.php): failed to open stream: No such file or directory
#0 D:\xampp7.0\htdocs\iot\api\app\Controllers\Login.php(11): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(./PHPMa...', 'D:\\xampp7.0\\htd...', 11, Array)
#1 D:\xampp7.0\htdocs\iot\api\app\Controllers\Login.php(11): require()
#2 D:\xampp7.0\htdocs\iot\api\system\Autoloader\Autoloader.php(300): include_once('D:\\xampp7.0\\htd...')
#3 D:\xampp7.0\htdocs\iot\api\system\Autoloader\Autoloader.php(273): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp7.0\\htd...')
#4 D:\xampp7.0\htdocs\iot\api\system\Autoloader\Autoloader.php(247): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#5 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#6 [internal function]: spl_autoload_call('App\\Controllers...')
#7 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(885): class_exists('\\App\\Controller...', true)
#8 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(421): CodeIgniter\CodeIgniter->startController()
#9 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-09-02 19:35:28 --> CodeIgniter\Autoloader\Autoloader::main(): Failed opening required './PHPMailer/Exception.php' (include_path='D:\xampp7.0\php\PEAR')
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-09-02 19:57:09 --> trim() expects parameter 1 to be string, array given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'trim() expects ...', 'D:\\xampp7.0\\htd...', 1078, Array)
#1 D:\xampp7.0\htdocs\iot\api\app\Controllers\PHPMailer\PHPMailer.php(1078): trim(Array)
#2 D:\xampp7.0\htdocs\iot\api\app\Controllers\PHPMailer\PHPMailer.php(1014): PHPMailer\PHPMailer\PHPMailer->addOrEnqueueAnAddress('to', Array, 'jorge')
#3 D:\xampp7.0\htdocs\iot\api\app\Controllers\Login.php(74): PHPMailer\PHPMailer\PHPMailer->addAddress(Array, 'jorge')
#4 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Login->RestablecerPassword()
#5 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#6 D:\xampp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
=======
CRITICAL - 2021-09-02 17:28:39 --> Class 'App\Models\ClienteMaquinaModel' not found
#0 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(900): App\Controllers\Administrador->__construct()
#1 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(426): CodeIgniter\CodeIgniter->createController()
#2 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 A:\Programas\xamp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-09-02 17:32:03 --> Class 'App\Models\ClienteMaquinaModel' not found
#0 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(900): App\Controllers\Administrador->__construct()
#1 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(426): CodeIgniter\CodeIgniter->createController()
#2 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 A:\Programas\xamp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2021-09-02 17:33:36 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `maquina` FOREIGN KEY (`idMaquina`) REFERENCES `maquinas` (`idMaquina`))
CRITICAL - 2021-09-02 17:33:36 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `maquina` FOREIGN KEY (`idMaquina`) REFERENCES `maquinas` (`idMaquina`))
#0 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `cl...')
#1 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 A:\Programas\xamp7.0\htdocs\iot\api\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 A:\Programas\xamp7.0\htdocs\iot\api\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 A:\Programas\xamp7.0\htdocs\iot\api\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#7 A:\Programas\xamp7.0\htdocs\iot\api\app\Controllers\Administrador.php(176): CodeIgniter\Model->insert()
#8 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Administrador->AsignarMaquina()
#9 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Administrador))
#10 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 A:\Programas\xamp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2021-09-02 17:34:30 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `maquina` FOREIGN KEY (`idMaquina`) REFERENCES `maquinas` (`idMaquina`))
CRITICAL - 2021-09-02 17:34:30 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `maquina` FOREIGN KEY (`idMaquina`) REFERENCES `maquinas` (`idMaquina`))
#0 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `cl...')
#1 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 A:\Programas\xamp7.0\htdocs\iot\api\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 A:\Programas\xamp7.0\htdocs\iot\api\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 A:\Programas\xamp7.0\htdocs\iot\api\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#7 A:\Programas\xamp7.0\htdocs\iot\api\app\Controllers\Administrador.php(176): CodeIgniter\Model->insert()
#8 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Administrador->AsignarMaquina()
#9 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Administrador))
#10 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 A:\Programas\xamp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2021-09-02 17:39:15 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `maquina` FOREIGN KEY (`idMaquina`) REFERENCES `maquinas` (`idMaquina`))
CRITICAL - 2021-09-02 17:39:15 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `maquina` FOREIGN KEY (`idMaquina`) REFERENCES `maquinas` (`idMaquina`))
#0 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `cl...')
#1 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 A:\Programas\xamp7.0\htdocs\iot\api\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 A:\Programas\xamp7.0\htdocs\iot\api\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 A:\Programas\xamp7.0\htdocs\iot\api\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#7 A:\Programas\xamp7.0\htdocs\iot\api\app\Controllers\Administrador.php(176): CodeIgniter\Model->insert()
#8 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Administrador->AsignarMaquina()
#9 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Administrador))
#10 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 A:\Programas\xamp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2021-09-02 17:57:01 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `maquina` FOREIGN KEY (`idMaquina`) REFERENCES `maquinas` (`idMaquina`))
CRITICAL - 2021-09-02 17:57:01 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `maquina` FOREIGN KEY (`idMaquina`) REFERENCES `maquinas` (`idMaquina`))
#0 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `cl...')
#1 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 A:\Programas\xamp7.0\htdocs\iot\api\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 A:\Programas\xamp7.0\htdocs\iot\api\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 A:\Programas\xamp7.0\htdocs\iot\api\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#7 A:\Programas\xamp7.0\htdocs\iot\api\app\Controllers\Administrador.php(187): CodeIgniter\Model->insert()
#8 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Administrador->AsignarMaquina()
#9 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Administrador))
#10 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 A:\Programas\xamp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2021-09-02 18:03:12 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `maquina` FOREIGN KEY (`idMaquina`) REFERENCES `maquinas` (`idMaquina`))
CRITICAL - 2021-09-02 18:03:12 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `maquina` FOREIGN KEY (`idMaquina`) REFERENCES `maquinas` (`idMaquina`))
#0 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `cl...')
#1 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 A:\Programas\xamp7.0\htdocs\iot\api\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 A:\Programas\xamp7.0\htdocs\iot\api\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 A:\Programas\xamp7.0\htdocs\iot\api\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#7 A:\Programas\xamp7.0\htdocs\iot\api\app\Controllers\Administrador.php(187): CodeIgniter\Model->insert()
#8 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Administrador->AsignarMaquina()
#9 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Administrador))
#10 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 A:\Programas\xamp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2021-09-02 18:05:21 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `usuario` FOREIGN KEY (`idUsuario`) REFERENCES `usuarios` (`idUsuario`))
CRITICAL - 2021-09-02 18:05:21 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `usuario` FOREIGN KEY (`idUsuario`) REFERENCES `usuarios` (`idUsuario`))
#0 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `cl...')
#1 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 A:\Programas\xamp7.0\htdocs\iot\api\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 A:\Programas\xamp7.0\htdocs\iot\api\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 A:\Programas\xamp7.0\htdocs\iot\api\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#7 A:\Programas\xamp7.0\htdocs\iot\api\app\Controllers\Administrador.php(187): CodeIgniter\Model->insert()
#8 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Administrador->AsignarMaquina()
#9 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Administrador))
#10 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 A:\Programas\xamp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2021-09-02 18:05:32 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `usuario` FOREIGN KEY (`idUsuario`) REFERENCES `usuarios` (`idUsuario`))
CRITICAL - 2021-09-02 18:05:32 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `usuario` FOREIGN KEY (`idUsuario`) REFERENCES `usuarios` (`idUsuario`))
#0 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `cl...')
#1 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 A:\Programas\xamp7.0\htdocs\iot\api\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 A:\Programas\xamp7.0\htdocs\iot\api\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 A:\Programas\xamp7.0\htdocs\iot\api\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#7 A:\Programas\xamp7.0\htdocs\iot\api\app\Controllers\Administrador.php(187): CodeIgniter\Model->insert()
#8 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Administrador->AsignarMaquina()
#9 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Administrador))
#10 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 A:\Programas\xamp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2021-09-02 18:05:35 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `usuario` FOREIGN KEY (`idUsuario`) REFERENCES `usuarios` (`idUsuario`))
CRITICAL - 2021-09-02 18:05:35 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `usuario` FOREIGN KEY (`idUsuario`) REFERENCES `usuarios` (`idUsuario`))
#0 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `cl...')
#1 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 A:\Programas\xamp7.0\htdocs\iot\api\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 A:\Programas\xamp7.0\htdocs\iot\api\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 A:\Programas\xamp7.0\htdocs\iot\api\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#7 A:\Programas\xamp7.0\htdocs\iot\api\app\Controllers\Administrador.php(187): CodeIgniter\Model->insert()
#8 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Administrador->AsignarMaquina()
#9 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Administrador))
#10 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 A:\Programas\xamp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2021-09-02 18:06:27 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `maquina` FOREIGN KEY (`idMaquina`) REFERENCES `maquinas` (`idMaquina`))
CRITICAL - 2021-09-02 18:06:27 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `maquina` FOREIGN KEY (`idMaquina`) REFERENCES `maquinas` (`idMaquina`))
#0 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `cl...')
#1 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 A:\Programas\xamp7.0\htdocs\iot\api\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 A:\Programas\xamp7.0\htdocs\iot\api\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 A:\Programas\xamp7.0\htdocs\iot\api\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 A:\Programas\xamp7.0\htdocs\iot\api\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#7 A:\Programas\xamp7.0\htdocs\iot\api\app\Controllers\Administrador.php(187): CodeIgniter\Model->insert()
#8 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Administrador->AsignarMaquina()
#9 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Administrador))
#10 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 A:\Programas\xamp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2021-09-02 18:08:47 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `maquina` FOREIGN KEY (`idMaquina`) REFERENCES `maquinas` (`idMaquina`))
ERROR - 2021-09-02 18:09:19 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `maquina` FOREIGN KEY (`idMaquina`) REFERENCES `maquinas` (`idMaquina`))
ERROR - 2021-09-02 18:09:27 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `maquina` FOREIGN KEY (`idMaquina`) REFERENCES `maquinas` (`idMaquina`))
ERROR - 2021-09-02 18:13:08 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `usuario` FOREIGN KEY (`idUsuario`) REFERENCES `usuarios` (`idUsuario`))
ERROR - 2021-09-02 18:37:20 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `usuario` FOREIGN KEY (`idUsuario`) REFERENCES `usuarios` (`idUsuario`))
ERROR - 2021-09-02 18:37:28 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `usuario` FOREIGN KEY (`idUsuario`) REFERENCES `usuarios` (`idUsuario`))
ERROR - 2021-09-02 18:37:33 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `usuario` FOREIGN KEY (`idUsuario`) REFERENCES `usuarios` (`idUsuario`))
ERROR - 2021-09-02 18:37:40 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `usuario` FOREIGN KEY (`idUsuario`) REFERENCES `usuarios` (`idUsuario`))
ERROR - 2021-09-02 18:38:12 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `usuario` FOREIGN KEY (`idUsuario`) REFERENCES `usuarios` (`idUsuario`))
ERROR - 2021-09-02 18:38:37 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `usuario` FOREIGN KEY (`idUsuario`) REFERENCES `usuarios` (`idUsuario`))
ERROR - 2021-09-02 18:38:57 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `usuario` FOREIGN KEY (`idUsuario`) REFERENCES `usuarios` (`idUsuario`))
ERROR - 2021-09-02 18:39:22 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `usuario` FOREIGN KEY (`idUsuario`) REFERENCES `usuarios` (`idUsuario`))
ERROR - 2021-09-02 18:39:31 --> Cannot add or update a child row: a foreign key constraint fails (`iot`.`clientesmaquinas`, CONSTRAINT `usuario` FOREIGN KEY (`idUsuario`) REFERENCES `usuarios` (`idUsuario`))
>>>>>>> 0bf8740a5357f5b6cf673ee62aafa578e8a01bb7
CRITICAL - 2021-09-02 21:37:00 --> Undefined property: App\Controllers\Registro::$administrador
#0 A:\Programas\xamp7.0\htdocs\iot\api\app\Controllers\Registro.php(70): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'A:\\Programas\\xa...', 70, Array)
#1 A:\Programas\xamp7.0\htdocs\iot\api\app\Controllers\Registro.php(33): App\Controllers\Registro->Existe('otromail@gmail....')
#2 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Registro->AltaUsuario()
#3 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registro))
#4 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 A:\Programas\xamp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-09-02 21:40:49 --> Undefined property: App\Controllers\Registro::$administrador
#0 A:\Programas\xamp7.0\htdocs\iot\api\app\Controllers\Registro.php(70): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'A:\\Programas\\xa...', 70, Array)
#1 A:\Programas\xamp7.0\htdocs\iot\api\app\Controllers\Registro.php(33): App\Controllers\Registro->Existe('otromail@gmail....')
#2 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Registro->AltaUsuario()
#3 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registro))
#4 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 A:\Programas\xamp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-09-02 21:41:12 --> Undefined offset: 0
#0 A:\Programas\xamp7.0\htdocs\iot\api\app\Controllers\Registro.php(33): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', 'A:\\Programas\\xa...', 33, Array)
#1 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Registro->AltaUsuario()
#2 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registro))
#3 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 A:\Programas\xamp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-02 21:42:12 --> Undefined offset: 0
#0 A:\Programas\xamp7.0\htdocs\iot\api\app\Controllers\Registro.php(33): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', 'A:\\Programas\\xa...', 33, Array)
#1 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Registro->AltaUsuario()
#2 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registro))
#3 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 A:\Programas\xamp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-02 21:42:40 --> Undefined offset: 0
#0 A:\Programas\xamp7.0\htdocs\iot\api\app\Controllers\Registro.php(33): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', 'A:\\Programas\\xa...', 33, Array)
#1 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(928): App\Controllers\Registro->AltaUsuario()
#2 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registro))
#3 A:\Programas\xamp7.0\htdocs\iot\api\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 A:\Programas\xamp7.0\htdocs\iot\api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
